#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

space_count=$(yabai -m query --spaces | jq '. | length')
while [ "$space_count" -lt 6 ]; do
    yabai -m space --create
    space_count=$((space_count + 1))
done
while [ "$space_count" -gt 6 ]; do
    yabai -m space --destroy "$space_count"
    space_count=$((space_count - 1))
done

yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config window_gap 0

yabai -m config split_ratio  0.50
yabai -m config auto_balance on
yabai -m config window_animation_duration 0.0

yabai -m rule --add app="^(System Settings|Finder|Calculator|Archive Utility)$" manage=off

yabai -m rule --add label=terminal app="^Ghostty$" space=1
yabai -m rule --add label=browser  app="^Firefox$" space=2
yabai -m rule --add label=cinny    app="^Cinny$"    space=3
yabai -m rule --add label=signal   app="^Signal$"   space=3
yabai -m rule --add label=discord  app="^Vesktop$"  space=3
yabai -m rule --add label=telegram app="^Telegram$" space=3
normal_spaces() { yabai -m query --spaces | jq '[.[] | select(."is-native-fullscreen" | not)]'; }
[ "$(normal_spaces | jq length)" -lt 3 ] && yabai -m space --create
yabai -m space "$(normal_spaces | jq '.[-1].index')" --label obs
yabai -m rule --add label=obs app="^OBS Studio$" space=obs

yabai -m rule --apply
